# Generated by Django 4.1.4 on 2022-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_tags_projectid_tags_projectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='projectId',
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(to='projects.tags'),
        ),
    ]
