# Generated by Django 4.1.4 on 2022-12-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='extra_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
