# Generated by Django 4.1.4 on 2022-12-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projects_extra_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(related_name='projects', to='projects.tags'),
        ),
    ]
