# Generated by Django 4.1.4 on 2022-12-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projects_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='projects.tags'),
        ),
    ]
