# Generated by Django 4.1.4 on 2022-12-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projects_github_link_projects_live_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.tags'),
        ),
    ]
